---
- name: Bluehost backups
  hosts: bluehost
  sudo: False
  vars_files:
    - vars.yml

  tasks:

    - name: Create Backups folder
      file: path={{ remote_bk_dir }} state=directory
      tags:
        - folders
        - databases

    - name: Dump databases
      mysql_db: login_user={{ db_user }} login_host={{ db_host }} login_password={{ db_pass }} name={{ item }} state=dump target={{ remote_bk_dir }}{{ item }}Db.sql.gz
      with_items: databases
      tags:
        - databases

    - name: Compress sites folders
      command: tar -zcvf {{ remote_bk_dir }}{{ item }}.tar {{ item }}
      with_items: folders
      tags:
        - folders

    - name: Fetch databases backups
      fetch: src={{ remote_bk_dir }}{{ item }}Db.sql.gz dest={{ local_bk_dir }}
      with_items: databases
      tags:
        - databases

    - name: Fetch folders backups
      fetch: src={{ remote_bk_dir }}{{ item }}.tar dest={{ local_bk_dir }}
      with_items: folders
      tags:
        - folders

    - name: Delete temp backup folder from server
      file: path={{ remote_bk_dir }} state=absent
      tags:
        - folders
        - databases

    - name: Send email notification
      local_action: mail msg='System {{ ansible_hostname }} has been successfully backed up.'
                    subject="Ansible-report"
                    body="This databases has been backed up {{ databases }}"
                    from="server@email.com (Bluehost)"
                    to="Your Name <your@jemail.com>"
      ignore_errors: true
      tags:
        - folders
        - databases
        - notification

